services:
    belabox-receiver:
        container_name: belabox-receiver
        ports:
            - '5000:5000/udp'
            - '8181:8181'
            - '8282:8282/udp'
        volumes:
            - './config.json:/app/config.json'
        image: datagutt/belabox-receiver
